pipeline {
    agent any
    
    triggers {
        pollSCM('* * * * *')
    }
    
    stages {
        stage("Compile") {
            steps {
                sh "cd Chapter08/sample1 && ./gradlew compileJava"
            }
        }
        
        stage("Unit test") {
            steps {
                sh "cd Chapter08/sample1 && ./gradlew test"
            }
        }
        
        stage("Code coverage") {
            steps {
                sh "cd Chapter08/sample1 && ./gradlew jacocoTestReport"
            }
        }
        
        stage('Test Coverage') {
            steps {
                sh 'cd Chapter08/sample1 && ./gradlew jacocoTestCoverageVerification'
            }
        }

        stage('Checkstyle') {
            steps {
                sh 'cd Chapter08/sample1 && ./gradlew checkstyleTest || true'
            }
            post {
                always {
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                        reportFiles: 'test.html', 
                        reportName: 'jacoco checkstyle'
                    ])
                }
            }
        }
        
        stage("Static code analysis") {
            steps {
                sh "cd Chapter08/sample1 && ./gradlew checkstyleMain"
            }
        }
        
        stage("Package") {
            steps {
                sh "cd Chapter08/sample1 && ./gradlew build"
            }
        }
    }
}
