pipeline {
    agent { 
        docker { 
            image 'gradle:jdk17'
            args '-v /var/jenkins_home/.gradle:/home/gradle/.gradle'
        } 
    }
    stages {
        stage('Validate Branch') {
            steps {
                script {
                    if (env.BRANCH_NAME != 'master' && !env.BRANCH_NAME.contains('feature')) {
                        error "Pipeline failed: Branch '${env.BRANCH_NAME}' is not allowed."
                    }
                }
            }
        }
        stage('CodeCoverage') {
            when { branch 'master' } // Ensure this matches your branch name (master or main)
            steps { sh 'cd Chapter08/sample1 && ./gradlew jacocoTestReport' }
        }
        stage('Run Tests') {
            when {
                allOf {
                    branch 'feature*'
                    not { branch 'master' }
                }
            }
            steps { sh 'cd Chapter08/sample1 && ./gradlew test' }
        }
    }
}
